### ISSUE TITLE
Automatically set {x, y} extended ticks to a lighter opacity

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#118]
Right now, we have selectors outside of the library's css file, i.e. in css/metrics-graphics-demo.css, that do this:

``` css
.extended-y-ticks svg .y-axis line {
    opacity: 0.1;
}

.extended-x-ticks svg .x-axis line {
    opacity: 0.1;
}
```

It might be a good idea to move those to the library's style sheets instead, since the lighter opacity for extended ticks seems to be the desired look everywhere that we've used them.
