### ISSUE TITLE
axis lables e.a. positioned fixed

### ISSUE THREAD

**Issue by thesec** [mozilla/metrics-graphics#410]
E.g. secondary x-axis labels do not account for changed font-sizes, causing overlappings with x-axis labels.

**Comment by almossawi** [comment]
We could, I suppose, handle potential collisions here the same way we handle them for markers and labels, rather than mitigating the issue like so 

```css
.mg-year-marker {
    transform: translateY(2px);
}
```

Let's keep this issue open for now.
