### ISSUE TITLE
Question: Style baseline and annotation

### ISSUE THREAD

**Issue by kayazinc** [mozilla/metrics-graphics#696]
Is there any api to style the baseline or marker?
Example, changing the stroke color:
```
    var action_markers = [
        {'date': new Date('2016-01-07'), 'label': 'start', style: 'startcss'},
        {'date': new Date('2016-01-13'), 'label': 'end', style: 'endcss'}
    ];
```
```css
.startcss {
  stroke: red;
}
.endcss {
  stroke: blue;
}
```
